spring.application.name=routing-service

# Configuracoes de Conexao com o PostgreSQL (via Variaveis de Ambiente para a Nuvem)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Configuracao do Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate e JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Executar o script schema.sql na inicializacao
spring.sql.init.mode=always