spring.application.name=routing-service

# Configuracoes de Conexao com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/flowpay_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Configuracao do Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Executar o script schema.sql na inicializacao
spring.sql.init.mode=always